services:
  btb:
    image: itzg/minecraft-server
    restart: always
    volumes:
      - "./assets/map-world:/data/template:ro"
      - "./assets/datapack:/data/datapacks/btb:ro"
      - "./assets/lobby-world:/worlds/lobby:ro"
      - "./build/libs/btb-1.0-SNAPSHOT.jar:/plugins/btb-1.0-SNAPSHOT.jar:ro"
      - "./assets/patches/dev:/patches:ro"
    env_file:
      - path: .env.dev
        required: false
    environment:
      - "EULA=true"
      - "TYPE=PAPER"
      - "MEMORY=2G"
      - "VERSION=1.21.4"
      - "SPAWN_PROTECTION=0"
      - "WORLD=/worlds/lobby"
      - "FORCE_WORLD_COPY=true"
      - "DATAPACKS=/data/datapacks/btb"
      - "PATCH_DEFINITIONS=/patches"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"