services:
  btb:
    image: itzg/minecraft-server
    restart: always
    volumes:
      - "./assets/map-world:/data/template:ro"
      - "./assets/datapack:/worlds/lobby/datapacks/btb:ro"
      - "./assets/lobby-world:/worlds/lobby:ro"
      - "./build/libs/btb-1.0-SNAPSHOT.jar:/plugins/btb-1.0-SNAPSHOT.jar:ro"
    environment:
      - "EULA=true"
      - "TYPE=PAPER"
      - "MEMORY=2G"
      - "VERSION=1.21.4"
      - "SPAWN_PROTECTION=0"
      - "WORLD=/worlds/lobby"
      - "FORCE_WORLD_COPY=TRUE"
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"