services:
  btb:
    image: itzg/minecraft-server
    restart: always
    volumes:
      - "./assets/map-world:/data/template:ro"
      - "./assets/lobby-world:/worlds/lobby:ro"
      - "./assets/datapack:/datapacks/btb:ro"
      - "./build/libs/btb-1.0-SNAPSHOT.jar:/plugins/btb-1.0-SNAPSHOT.jar:ro" # TODO build with nix or fetch from github
      - "./assets/patches/prod:/patches:ro"
    env_file: .env.prod
    environment:
      - "EULA=true"
      - "TYPE=paper"
      - "MEMORY=2G"
      - "VERSION=1.21.4"
      - "SPAWN_PROTECTION=0"
      - "WORLD=/worlds/lobby"
      - "FORCE_WORLD_COPY=true"
      - "DATAPACKS=/datapacks/btb"
      - "PATCH_DEFINITIONS=/patches"
    networks:
      - velocity

networks:
  velocity:
    external: true