name: BTB
version: '${version}'
main: de.tert0.btb.BTB
api-version: '1.21'

commands:
  btbteam:
    description: Join BTB Team
  btbrole:
    description: Select a Role
  start:
    description: Start a BTB Game
    permission: btb.start

permissions:
  btb.start:
    description: "Allows you to use the command /start to instantly start a game"
    default: op