services:
  lobby-server:
    image: itzg/minecraft-server
    environment:
      - "EULA=true"
      - "TYPE=paper"
      - "VERSION=1.21.4"
      - "MEMORY=2G"
      - "DATAPACKS=/data/datapacks/btb"
      - "MODE=creative"
      - "LEVEL_TYPE=minecraft:flat"
      - "DIFFICULTY=peaceful"
      - "PLUGINS=https://github.com/IntellectualSites/FastAsyncWorldEdit/releases/download/2.12.3/FastAsyncWorldEdit-Paper-2.12.3.jar"
    env_file: .env
    volumes:
      - "${WORLD_PATH:?error}:/data/world"
      - "./datapack:/data/datapacks/btb:ro"
    ports:
      - "25565:25565"